import {Dimensions, StyleSheet} from 'react-native';
const screenHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  indicatorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 18,
    paddingTop: 10,
    paddingBottom: 4,
  },
  headerSeperator: {
    backgroundColor: '#888888',
    width: 3,
  },
  spotTitle: {
    fontSize: 12,
    paddingBottom: 4,
  },
  time: {
    color: '#999999',
    paddingBottom: 4,
    fontSize: 12,
  },
  nextNewsTextContainer: {
    top: 2,
    zIndex: 1,
    alignSelf: 'baseline',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  nextNewsDottedContainer: {
    width: '100%',
    height: screenHeight / 8,
    borderWidth: 2,
    borderStyle: 'dotted',
    borderRadius: 10,
    // borderColor: 'gray',
    flexDirection: 'row',
    marginBottom: 20,
  },
  nextNewsImage: {
    aspectRatio: 1 / 1,
    borderBottomLeftRadius: 10,
    height: '103%',
    left: -2,
  },
  nextNewsTitle: {
    fontSize: 16,
    alignSelf: 'center',
  },
  nextNewsButton: {
    width: 40,
    height: 40,
    // backgroundColor: 'blue',

    position: 'absolute',
    right: 0,
    margin: 5,
  },
  image: {
    // aspectRatio: 16 / 9,
    // backgroundColor: 'black',
  },
  description: {
    fontSize: 14,
    paddingTop: 10,
  },
  video: {
    aspectRatio: 16 / 9,
    borderRadius: 10,
    backgroundColor: 'black',
  },
  socialMediaContainer: {
    position: 'absolute',
    flexDirection: 'row',
    top: '35%',
    justifyContent: 'center',
    width: '100%',
  },
  socialMediaIcon: {
    width: 50,
    height: 50,
    marginLeft: 5,
    // alignItems: 'flex-end',
    // justifyContent: 'flex-end',
  },
  shareContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  shareButtonContainer: {
    top: 0,
    margin: 10,
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  shareButtonContainerV2: {
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    zIndex: 2,
    position: 'absolute',
  },
  shareButton: {
    width: 30,
    height: 30,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  shareButtonV2: {
    width: 30,
    height: 30,
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
  },
  videoCoverImage: {
    aspectRatio: 16 / 9,
    borderRadius: 10,
  },
  videoCoverPlayIcon: {
    width: 30,
    height: 30,
    position: 'absolute',
    top: '40%',
    alignSelf: 'center',
  },
  yatayTekliDottedContainer: {
    width: '100%',
    height: screenHeight / 4.5,
    borderWidth: 2,
    borderStyle: 'dotted',
    borderRadius: 10,
    borderColor: 'gray',
    flexDirection: 'row',
  },
  yatayTekliImage: {
    aspectRatio: 1 / 1,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    height: '103%',
    bottom: 2,
    left: -2,
  },
  yatayTekliIcon: {
    width: 30,
    height: 30,
    //borderRadius: 20,
    // borderWidth: 2,
    // borderColor: 'white',
    // right: 15,
    // top: 5,
    //backgroundColor: 'white',
  },
});
