export default {
  IntroPage: 'IntroPage',
  Menu: 'menu',
  HomePage: 'HomePage',
  HomeStack: 'HomeStack',
  Garden: 'Garden',
  Agro: 'Agro',
  Blog: 'Blog',
  VegetableMarket: 'VegetableMarket',
  Settings: 'Settings',
  Camera: 'Camera',
  Login: 'Login',
  Register: 'Register',
  Profile: 'Profile',
  Weather: 'Weather',
  NewsPage: 'NewsPage',
  Medicine: 'Medicine',
  ChatPage: 'ChatPage',
  MessagePage: 'MessagePage',
  MyGardenPage: 'MyGardenPage',
  //SplashScreen: 'SplashScreen',
};
